# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Festerize < Formula
  desc "Uploads CSV files to the Fester IIIF manifest service for processing"
  homepage "https://github.com/UCLALibrary/go-festerize"
  version "0.4.3"

  on_macos do
    on_intel do
      url "https://github.com/UCLALibrary/go-festerize/releases/download/v0.4.3/festerize_Darwin_x86_64.zip"
      sha256 "813e9710c95dbe9192a2cf221e8f694e44b4e217442d6410ce8ebadc6f2323c9"

      def install
        bin.install "festerize"
      end
    end
    on_arm do
      url "https://github.com/UCLALibrary/go-festerize/releases/download/v0.4.3/festerize_Darwin_arm64.zip"
      sha256 "8ecca51a3d58ce5069dbbaf01d742db9053f19429712c211f81641e752684ba9"

      def install
        bin.install "festerize"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UCLALibrary/go-festerize/releases/download/v0.4.3/festerize_Linux_x86_64.tar.gz"
        sha256 "3a79e08ad6d8012214730348e46f8e31d83d1012865995778b4605300c6851db"

        def install
          bin.install "festerize"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UCLALibrary/go-festerize/releases/download/v0.4.3/festerize_Linux_arm64.tar.gz"
        sha256 "8924c6e82e51e6b94d12aeba77cabf2638f8cdd8776d2561d2a6e974605f1d97"

        def install
          bin.install "festerize"
        end
      end
    end
  end
end
