# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Festerize < Formula
  desc "Uploads CSV files to the Fester IIIF manifest service for processing"
  homepage "https://github.com/UCLALibrary/go-festerize"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UCLALibrary/go-festerize/releases/download/0.5.0/festerize_Darwin_x86_64.zip"
      sha256 "8986bbb4e3ca06df0e1deb2621d88370b0ea4ea1efa4ec60961a15f941109696"

      def install
        bin.install "festerize"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UCLALibrary/go-festerize/releases/download/0.5.0/festerize_Darwin_arm64.zip"
      sha256 "53dd6a029f1be1b804f0eeda1549b24e6781ea6c3548c2f56748662ce3ca8d73"

      def install
        bin.install "festerize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/UCLALibrary/go-festerize/releases/download/0.5.0/festerize_Linux_x86_64.tar.gz"
      sha256 "b40a31337430be06b1b4cd0ac6146df9607b26f6cfef5ec786ef817ac9cb2689"
      def install
        bin.install "festerize"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/UCLALibrary/go-festerize/releases/download/0.5.0/festerize_Linux_arm64.tar.gz"
      sha256 "218f01ea81faaf7b7f99dc333248167e027a4353f8a13145a059e11b831efb72"
      def install
        bin.install "festerize"
      end
    end
  end
end
