# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Festerize < Formula
  desc "Uploads CSV files to the Fester IIIF manifest service for processing"
  homepage "https://github.com/UCLALibrary/go-festerize"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/UCLALibrary/go-festerize/releases/download/0.5.0/festerize_Darwin_x86_64.zip"
      sha256 "1a257bd86fdff87b9a3d32e774fe78fad9c0dcf4710be25e648d02f83ce70217"

      def install
        bin.install "festerize"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/UCLALibrary/go-festerize/releases/download/0.5.0/festerize_Darwin_arm64.zip"
      sha256 "a46c11c3bfe1e6cebcc2acc15a65cb2749a85cdd490f091777b992c9f626ee58"

      def install
        bin.install "festerize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/UCLALibrary/go-festerize/releases/download/0.5.0/festerize_Linux_x86_64.tar.gz"
      sha256 "62f7f4f383c510bdc893527adb627ef6055c10c718d9a5d3691139b00ef90985"
      def install
        bin.install "festerize"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/UCLALibrary/go-festerize/releases/download/0.5.0/festerize_Linux_arm64.tar.gz"
      sha256 "fc3c1cde04d892ee2206374ed6e6c4e34aad57494bb63e169cb0eebb89ffcbda"
      def install
        bin.install "festerize"
      end
    end
  end
end
